[package]
name = "ee"
version = "1.5.2"
edition = "2021"
description = "Easy Editor - A simple terminal-based text editor"
authors = ["Hugh Mahon"]

[dependencies]
ncurses = "5.101.0"
libc = "0.2"
gettext-rs = "0.7"
users = "0.11"
thiserror = "1.0"
tui = "0.19"
crossterm = "0.25"
syntect = "5.0"
